=== paulkoba/Assignments_KNU_Y3/distributed/7/Lab7/target/classes/data.dtd
<!ELEMENT Storage (NewsCategory*)>
        <!ELEMENT NewsCategory (Article*)>
        <!ELEMENT Article (#PCDATA)>
        <!ATTLIST NewsCategory id CDATA #REQUIRED name CDATA #REQUIRED>
        <!ATTLIST Article id CDATA #REQUIRED categoryID CDATA #REQUIRED name CDATA #REQUIRED>

=== paulkoba/Assignments_KNU_Y3/distributed/7/Lab7/target/classes/data.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Storage SYSTEM "data.dtd">
<Storage><NewsCategory id="1" name="Politics"><Article categoryID="1" id="123" name="Extremely interesting article"/><Article categoryID="1" id="234" name="Completely unbiased story"/><Article categoryID="1" id="456" name="Suspiciously specific telling"/></NewsCategory><NewsCategory id="2" name="Technology">
    <Article categoryID="2" id="567" name="IPhone 19 Released"/><Article categoryID="2" id="678" name="Technical details on patching KDE 2 for FreeBSD"/></NewsCategory></Storage>
